name: elpcd_dart
description: 'Ferramenta para criação de PCDs e TTDs'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^4.1.0
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  flutter_simple_treeview: ^2.0.2
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  provider: ^4.3.2+2
  universal_html: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  hive_generator: ^0.8.2
  lint: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/gedalogo_270x270.png
